### ISSUE TITLE
Karma stopped working after node 20 upgrade 

### ISSUE THREAD

**Issue by takahirohonda** [mydatahack/portfolio-site-jekyll#2]
Error message

02 02 2024 19:52:27.975:ERROR [karma-server]: UncaughtException: Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/taka/code/mdh/portfolio-site-jekyll/code/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/taka/code/mdh/portfolio-site-jekyll/code/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/taka/code/mdh/portfolio-site-jekyll/code/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/taka/code/mdh/portfolio-site-jekyll/code/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/taka/code/mdh/portfolio-site-jekyll/code/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/taka/code/mdh/portfolio-site-jekyll/code/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/taka/code/mdh/portfolio-site-jekyll/code/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/taka/code/mdh/portfolio-site-jekyll/code/node_modules/loader-runner/lib/LoaderRunner.js:221:10)

**Comment by takahirohonda** [comment]
I deleted all the karma related modules and re-installed them with node 20. I still get the same error. So all the karma related packages should be the latest....

**Comment by takahirohonda** [comment]
```bash
npm_config_yes=true npx yarn-audit-fix
```

This didn't fix it...

**Comment by takahirohonda** [comment]
```bas
export NODE_OPTIONS=--openssl-legacy-provider
yarn test
```

This works...

**Comment by takahirohonda** [comment]
[tsl] ERROR in /node_modules/@types/node/ts4.8/test.d.ts(914,34)
      TS1005: '?' expected


More error 😢

**Comment by takahirohonda** [comment]
I needed to upgrade typescript from 3.7.3 to 5.3.3
